/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.szydlowski.logwebse;

/**
 *
 * @author Dominik
 */
public class HtmlStyle {
    
    public static final String TOPNAV_STYLE = new StringBuilder().append("<style>\n .topnav {\n" )
                .append("  background-color: #333;\n" )
                .append("  overflow: hidden;\n" )
                .append("}\n" )
                .append("\n" )
                .append("/* Style the links inside the navigation bar */\n" )
                .append(".topnav a {\n" )
                .append("  float: left;\n" )
                .append("  color: #f2f2f2;\n" )
                .append("  text-align: center;\n" )
                .append("  padding: 14px 16px;\n" )
                .append("  text-decoration: none;\n" )
                .append("  font-size: 17px;\n" )
                .append("}\n" )
                .append("\n" )
                .append("/* Change the color of links on hover */\n" )
                .append(".topnav a:hover {\n" )
                .append("  background-color: #ddd;\n" )
                .append("  color: black;\n" )
                .append("}\n" )
                .append("\n" )
                .append("/* Add a color to the active/current link */\n" )
                .append(".topnav a.active {\n" )
                .append("  background-color: #4CAF50;\n" )
                .append("  color: white;\n" )
                .append("}</style>").toString();

   
    public static final String TABLE_STYLE= new StringBuilder().append("<style>\n")
            .append("body {font-family: Arial;}\n")
            .append("\n")
            .append("/* Style the tab */\n")
            .append(".tab {\n")
            .append("  overflow: hidden;\n")
            .append("  border: 1px solid #ccc;\n")
            .append("  background-color: #f1f1f1;\n")
            .append("}\n")
            .append("\n")
            .append("/* Style the buttons inside the tab */\n")
            .append(".tab button {\n")
            .append("  background-color: inherit;\n")
            .append("  float: left;\n")
            .append("  border: none;\n")
            .append("  outline: none;\n")
            .append("  cursor: pointer;\n")
            .append("  padding: 14px 16px;\n")
            .append("  transition: 0.3s;\n")
            .append("  font-size: 17px;\n")
            .append("}\n")
            .append("\n")
            .append("/* Change background color of buttons on hover */\n")
            .append(".tab button:hover {\n")
            .append("  background-color: #ddd;\n")
            .append("}\n")
            .append("\n")
            .append("/* Create an active/current tablink class */\n")
            .append(".tab button.active {\n")
            .append("  background-color: #4CAF50;\n")
            .append("}\n")
            .append("\n")
            .append("/* Style the tab content */\n")
            .append(".tabcontent {\n")
            .append("  display: none;\n")
            .append("  padding: 6px 12px;\n")
            .append("  -webkit-animation: fadeEffect 1s;\n")
            .append("  animation: fadeEffect 1s;\n")
            .append("}\n")
            .append("\n")
            .append("/* Fade in tabs */\n")
            .append("@-webkit-keyframes fadeEffect {\n")
            .append("  from {opacity: 0;}\n")
            .append("  to {opacity: 1;}\n")
            .append("}\n")
            .append("\n")
            .append("@keyframes fadeEffect {\n")
            .append("  from {opacity: 0;}\n")
            .append("  to {opacity: 1;}\n")
            .append("}\n")
            .append("table {\n")
            .append("  font-family: arial, sans-serif;\n")
            .append("  border-collapse: collapse;\n")
            .append("  width: 60%;\n")
            .append("}\n")
            .append("\n")
            .append("td, th {\n")
            .append("  border: 1px solid #dddddd;\n")
            .append("  text-align: left;\n")
            .append("  padding: 8px;\n")
            .append("}\n")
            .append("\n")
            .append("tr:nth-child(even) {\n")
            .append("  background-color: #dddddd;\n")
            .append("}")
            .append("</style>").toString();
    
    public static  final String FORM = new StringBuilder().append("<style>\n")
            .append("form .input {float: left; border: 0; margin: 0; background: none;}\n")
            .append("form .szukaj, form #wyslij {font-family: calibri; letter-spacing: -1px; font-size: 1em; padding: 2px; color: gray;}\n")
            .append("\n")
            .append("/*ZAOKRĄGLENIA*/\n")
            .append("form .szukaj {border-radius: 3px 0 0 3px;}\n")
            .append("form .wyslij {border-radius: 0 3px 3px 0;}\n")
            .append("\n")
            .append("/*CIEŃ I USUWANIE OTOCZKI*/\n")
            .append("form .szukaj {box-shadow: 0 0 10px silver inset; -moz-outline: none; -webkit-outline: none; -o-outline: none; outline: none; }\n")
            .append("form .wyslij {cursor: pointer;}\n")
            .append("\n")
            .append("/*GRADIENT*/\n")
            .append("form .szukaj {\n")
            .append("background: #f2f2f2;\n")
            .append("background: -moz-linear-gradient(top, #f2f2f2 1%, #d6d6d6 100%);\n")
            .append("background: -webkit-gradient(linear, left top, left bottom, color-stop(1%,#f2f2f2), color-stop(100%,#d6d6d6));\n")
            .append("background: -webkit-linear-gradient(top, #f2f2f2 1%,#d6d6d6 100%);\n")
            .append("background: -o-linear-gradient(top, #f2f2f2 1%,#d6d6d6 100%);\n")
            .append("background: -ms-linear-gradient(top, #f2f2f2 1%,#d6d6d6 100%);\n")
            .append("background: linear-gradient(to bottom, #f2f2f2 1%,#d6d6d6 100%);\n")
            .append("filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f2f2f2', endColorstr='#d6d6d6',GradientType=0 );\n")
            .append("}\n")
            .append("\n")
            .append("/*CIEŃ TESKTU I GRADIENT*/\n")
            .append("form .wyslij {\n")
            .append("text-shadow: 0 0 1px white;\n")
            .append("background: #258dc8;\n")
            .append("background: -moz-linear-gradient(top, #258dc8 0%, #f9ca2f 0%, #ffea4f 0%, #f9ca2f 100%);\n")
            .append("background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#258dc8), color-stop(0%,#f9ca2f), color-stop(0%,#ffea4f), color-stop(100%,#f9ca2f));\n")
            .append("background: -webkit-linear-gradient(top, #258dc8 0%,#f9ca2f 0%,#ffea4f 0%,#f9ca2f 100%);\n")
            .append("background: -o-linear-gradient(top, #258dc8 0%,#f9ca2f 0%,#ffea4f 0%,#f9ca2f 100%);\n")
            .append("background: -ms-linear-gradient(top, #258dc8 0%,#f9ca2f 0%,#ffea4f 0%,#f9ca2f 100%);\n")
            .append("background: linear-gradient(to bottom, #258dc8 0%,#f9ca2f 0%,#ffea4f 0%,#f9ca2f 100%);\n")
            .append("filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#258dc8', endColorstr='#f9ca2f',GradientType=0 );\n")
            .append("\n")
            .append("}\n")
            .append("/*CIEŃ TEKSTU I GRADIENT*/\n")
            .append("form .wyslij:hover {\n")
            .append("text-shadow: 0 0 1px black;\n")
            .append("color: white;\n")
            .append("background: #82b8ff;\n")
            .append("background: -moz-linear-gradient(top, #82b8ff 1%, #18a5f2 100%);\n")
            .append("background: -webkit-gradient(linear, left top, left bottom, color-stop(1%,#82b8ff), color-stop(100%,#18a5f2));\n")
            .append("background: -webkit-linear-gradient(top, #82b8ff 1%,#18a5f2 100%);\n")
            .append("background: -o-linear-gradient(top, #82b8ff 1%,#18a5f2 100%);\n")
            .append("background: -ms-linear-gradient(top, #82b8ff 1%,#18a5f2 100%);\n")
            .append("background: linear-gradient(to bottom, #82b8ff 1%,#18a5f2 100%);\n")
            .append("filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#82b8ff', endColorstr='#18a5f2',GradientType=0 );\n")
            .append("}\n")
            .append("\n")
            .append("</style>").toString();
    
    
    public static final String LINKSTYLE = new StringBuilder().append("<style>\n")
            .append("a:link { color: #696; text-decoration: none; background-color: transparent }\n")
            .append("a:visited { color: red; text-decoration: none; background-color: transparent }\n")
            .append("a:hover { color: #c93; text-decoration: underline; background-color: transparent }\n")
            .append("a:active { color: #900; text-decoration: underline; background-color: transparent }\n")
            .append("</style>").toString();
      
    /**
     *
     */
    public static final String ALERTSTYLE = new StringBuilder().append("<style>\n")
            .append("  .alert {\n")
            .append("  padding: 20px;\n")
            .append("  background-color: #f44336;\n")
            .append("  color: white;\n")
            .append("}")
            .append("</style>").toString();
      
        public static final String INFOSTYLE = new StringBuilder().append("<style>\n")
            .append("  .info {\n" )
            .append("  padding: 20px;\n" )
            .append("  background-color: #1aa3ff;\n" )
            .append("  color: white;\n" )
            .append("}")
            .append("</style>").toString();
        
        public static final String OKSTYLE = new StringBuilder().append("<style>\n")
            .append("  .ok {\n" )
            .append("  padding: 20px;\n" )
            .append("  background-color: green;\n" )
            .append("  color: white;\n" )
            .append("}" )
            .append("</style>").toString();
      
       public static final String SCRIPTREMADD = new StringBuilder().append("  <SCRIPT language=\"javascript\">\n")
            .append("function add() {\n" )
            .append("\n" )
            .append("	//Create an input type dynamically.\n" )
            .append("	var element = document.createElement(\"input\");\n" )
            .append("\n" )
            .append("	//Assign different attributes to the element.\n" )
            .append("	\n" )
            .append("	element.setAttribute(\"list\", \"words\");\n" )
            .append("	element.setAttribute(\"name\", \"word\");\n" )
            .append("    element.setAttribute(\"id\", \"word\");\n" )
            .append("    element.setAttribute(\"size\", \"80\");\n" )
            .append("    element.setAttribute(\"class\", \"szukaj\");\n" )
            .append("	\n" )
            .append("	var foo = document.getElementById(\"fooBar\");\n" )
            .append("\n" )
            .append("	//Append the element in page (in span).\n" )
            .append("	foo.appendChild(document.createElement(\"br\"));\n" )
            .append("	foo.appendChild(element);\n" )
            .append("    \n" )
            .append("\n" )
            .append("}\n" )
            .append("\n" )
            .append("function rem() {\n" )
            .append("  \n" )
            .append("   var container = document.getElementById(\"fooBar\");\n" )
            .append("            \n" )
            .append("   \n" )
            .append("   if (container.childElementCount>3){\n" )
            .append("         // alert('Element exists!');\n" )
            .append("         container.removeChild(container.lastChild);\n" )
            .append("         container.removeChild(container.lastChild);\n" )
            .append("   } else { \n" )
            .append("         alert('There is nothing to remove');\n" )
            .append("   }\n" )
            .append("\n" )
            .append("\n" )
            .append("}\n" )
            .append("</SCRIPT>").toString();
       
        public static final String SCRIPTHIDDEN = new StringBuilder().append("<script>\n")
            .append("$('#ch_entirefile').change(function(){\n")
            .append("  if($(this).is(':checked'))    \n")
            .append("    $('#inp_last').prop('disabled','disabled')\n")
            .append("  else $('#inp_last').prop('disabled','')\n")
            .append("})\n")
            .append("</script>").toString();
        
        public static final String TABLE_STYLE_NEW = new StringBuilder().append("<style>\n body {font-family: Arial;}\n" )
            .append("/* Style the tab */\n" )
            .append(".tab {\n" )
            .append("  overflow: hidden;\n" )
            .append("  border: 1px solid #ccc;\n" )
            .append("  background-color: #f1f1f1;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Style the buttons inside the tab */\n" )
            .append(".tab button {\n" )
            .append("  background-color: inherit;\n" )
            .append("  float: left;\n" )
            .append("  border: none;\n" )
            .append("  outline: none;\n" )
            .append("  cursor: pointer;\n" )
            .append("  padding: 14px 16px;\n" )
            .append("  transition: 0.3s;\n" )
            .append("  font-size: 17px;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Change background color of buttons on hover */\n" )
            .append(".tab button:hover {\n" )
            .append("  background-color: #ddd;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Create an active/current tablink class */\n" )
            .append(".tab button.active {\n" )
            .append("  background-color: #4CAF50;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Style the tab content */\n" )
            .append(".tabcontent {\n" )
            .append("  display: none;\n" )
            .append("  padding: 6px 12px;\n" )
            .append("  -webkit-animation: fadeEffect 1s;\n" )
            .append("  animation: fadeEffect 1s;\n" )
            .append("}\n" )
            .append("\n" )
            .append("/* Fade in tabs */\n" )
            .append("@-webkit-keyframes fadeEffect {\n" )
            .append("  from {opacity: 0;}\n" )
            .append("  to {opacity: 1;}\n" )
            .append("}\n" )
            .append("\n" )
            .append("@keyframes fadeEffect {\n" )
            .append("  from {opacity: 0;}\n" )
            .append("  to {opacity: 1;}\n" )
            .append("}\n" )
            .append("table {\n" )
            .append("  font-family: arial, sans-serif;\n" )
            .append("  border-collapse: collapse;\n" )
            .append("  width: 80%;\n" )
            .append("}\n" )
            .append("\n" )
            .append("th {\n" )
            .append("  border: 1px solid #dddddd;\n" )
            .append("  text-align: left;\n" )
            .append("  background-color: #008CBA; \n")
            .append("  color: white;\n")
            .append("  padding: 8px;\n" )
            .append("}\n" )
            .append("td{\n" )
            .append("  border: 1px solid #dddddd;\n" )
            .append("  text-align: left;\n" )
            .append("  padding: 8px;\n" )
            .append("}\n" )
            .append("\n" )
            .append("tr:nth-child(even) {\n" )
            .append("  background-color: #cccccc;\n" )
            .append("}")
            .append("tr:nth-child(odd) {\n" )
            .append("  background-color: #f2f2f2;\n" )
            .append("}")
            .append("tr:hover {background-color:#4CAF50;}") //podswietlanie
            .append(".button-exc {\n")
            .append("  background-color: #008CBA; \n")
            .append("  border: none;\n")
            .append("  color: white;\n")
            .append("  padding: 3px 8px;\n")
            .append("  text-align: center;\n")
            .append("  text-decoration: none;\n")
            .append("  display: inline-block;\n")
            .append("  font-size: 16px;\n")
            .append("  margin: 2px 2px;\n")
            .append("  cursor: pointer;\n")
            .append("}")
            .append("table.scroll {\n")
            .append("    width: 1400px; /* 140px * 3 column + 16px scrollbar width */\n" )
            .append("    border-spacing: 0;\n" )
            .append("    border: 1px solid black;\n" )
            .append("}\n" )
            .append("\n" )
            .append("table.scroll tbody,\n" )
            .append("table.scroll thead tr { display: block; }\n" )
            .append("\n" )
            .append("table.scroll tbody {\n" )
            .append("    max-height: 400px;\n" )
            .append("    overflow-y: auto;\n" )
            .append("    overflow-x: hidden;\n" )
            .append("}\n" )
            .append("\n" )
            .append("table.scroll tbody td,\n" )
            .append("table.scroll thead th {\n" )
            .append("    width: 200px;\n" )
            .append("    border-right: 1px solid black;\n" )
            .append("}\n" )
            .append("\n" )
            .append("thead tr th { \n" )
            .append("    height: 30px;\n" )
            .append("    line-height: 30px;\n" )
            .append("    position: sticky;\n" )
            .append("    top: 0;")
            .append("}\n" )
            .append("\n" )
            .append("tbody { border-top: 2px solid black; }\n" )
            .append("\n" )
            .append("tbody td:last-child, thead th:last-child {\n" )
            .append("    border-right: none !important;\n" )
            .append("}")
            .append("</style>")
            .toString();
}
